# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Alunos/Desktop/Vinícius_Cantuária/Vinícius_Cantuária.cache/wt [current_project]
set_property parent.project_path C:/Users/Alunos/Desktop/Vinícius_Cantuária/Vinícius_Cantuária.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/Alunos/Desktop/Vinícius_Cantuária/Vinícius_Cantuária.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Alunos/Desktop/Vinícius_Cantuária/Vinícius_Cantuária.srcs/sources_1/new/soma1bit.vhd
  C:/Users/Alunos/Desktop/Vinícius_Cantuária/Vinícius_Cantuária.srcs/sources_1/new/soma3bits.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Alunos/Desktop/Vinícius_Cantuária/Vinícius_Cantuária.srcs/constrs_1/imports/Downloads/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Alunos/Desktop/Vinícius_Cantuária/Vinícius_Cantuária.srcs/constrs_1/imports/Downloads/Basys3_Master.xdc]


synth_design -top soma3bits -part xc7a35tcpg236-1


write_checkpoint -force -noxdef soma3bits.dcp

catch { report_utilization -file soma3bits_utilization_synth.rpt -pb soma3bits_utilization_synth.pb }
